export const BaseUrl = 'http://code.aldipee.com/';
export const Token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjRiZTMyN2JiZTlkZDdmYjRmODVlNDMiLCJpYXQiOjE2NTAyNjkwNjEsImV4cCI6MTY1MDI3MDg2MSwidHlwZSI6ImFjY2VzcyJ9.ha20gm6JDXQ93X6PQTBQEjLHZ3V0zymIi0fkAQ7dVQA';
