name: CI Prosses

on:
  workflow_dispatch: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: instalasi modules
        run: yarn

      - name: unit testing
        run: yarn test

  check-linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: instalasi modules
        run: yarn

      - name: cleaning codes
        run: yarn lint
